export const mockHourlyForecast = [
  {
    time: "Now",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+18°",
    precipitationChange: "13%",
  },
  {
    time: "12 AM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+18°",
    precipitationChange: "13%",
  },
  {
    time: "1 AM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+18°",
    precipitationChange: "0%",
  },
  {
    time: "2 AM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+18°",
    precipitationChange: "0%",
  },
  {
    time: "3 AM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+18°",
    precipitationChange: "0%",
  },
  {
    time: "4 AM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+18°",
    precipitationChange: "0%",
  },
  {
    time: "5 AM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+18°",
    precipitationChange: "0%",
  },
  {
    time: "6 AM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+18°",
    precipitationChange: "3%",
  },
  {
    time: "7 AM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+18°",
    precipitationChange: "22%",
  },
  {
    time: "8 AM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+19°",
    precipitationChange: "15%",
  },
  {
    time: "9 AM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+19°",
    precipitationChange: "10%",
  },
  {
    time: "10 AM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+19°",
    precipitationChange: "5%",
  },
  {
    time: "11 AM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+20°",
    precipitationChange: "0%",
  },
  {
    time: "12 PM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+20°",
    precipitationChange: "0%",
  },
  {
    time: "1 PM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+20°",
    precipitationChange: "0%",
  },
  {
    time: "2 PM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+21°",
    precipitationChange: "0%",
  },
  {
    time: "3 PM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+21°",
    precipitationChange: "2%",
  },
  {
    time: "4 PM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+21°",
    precipitationChange: "5%",
  },
  {
    time: "5 PM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+21°",
    precipitationChange: "7%",
  },
  {
    time: "6 PM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+20°",
    precipitationChange: "10%",
  },
  {
    time: "7 PM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+20°",
    precipitationChange: "12%",
  },
  {
    time: "8 PM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+19°",
    precipitationChange: "15%",
  },
  {
    time: "9 PM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+19°",
    precipitationChange: "20%",
  },
  {
    time: "10 PM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+18°",
    precipitationChange: "25%",
  },
  {
    time: "11 PM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+18°",
    precipitationChange: "30%",
  },
  {
    time: "12 AM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+17°",
    precipitationChange: "28%",
  },
  {
    time: "1 AM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+17°",
    precipitationChange: "25%",
  },
  {
    time: "2 AM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+17°",
    precipitationChange: "22%",
  },
  {
    time: "3 AM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+16°",
    precipitationChange: "20%",
  },
  {
    time: "4 AM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+16°",
    precipitationChange: "18%",
  },
  {
    time: "5 AM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+16°",
    precipitationChange: "15%",
  },
  {
    time: "6 AM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+16°",
    precipitationChange: "12%",
  },
  {
    time: "7 AM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+17°",
    precipitationChange: "10%",
  },
  {
    time: "8 AM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+17°",
    precipitationChange: "8%",
  },
  {
    time: "9 AM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+18°",
    precipitationChange: "5%",
  },
  {
    time: "10 AM",
    condition: "Sunny",
    code: 1000,
    isDay: false,
    temperature: "+18°",
    precipitationChange: "3%",
  },
  {
    time: "11 AM",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    temperature: "+18°",
    precipitationChange: "2%",
  },
];
