export const mockWeeklyForecast = [
  {
    date: "Today",
    day: "Monday",
    condition: "Sunny",
    code: 1000,
    isDay: true,
    tempMax: "+18°",
    tempMin: "+12°",
  },
  {
    date: "Tomorrow",
    day: "Tuesday",
    condition: "Cloudy",
    code: 1000,
    isDay: false,
    tempMax: "+18°",
    tempMin: "+12°",
  },
  {
    date: "September 17",
    day: "Wednesday",
    condition: "Rain",
    code: 1000,
    isDay: true,
    tempMax: "+18°",
    tempMin: "+12°",
  },
  {
    date: "September 18",
    day: "Thursday",
    condition: "Moderate rain at times",
    code: 1000,
    isDay: false,
    tempMax: "+18°",
    tempMin: "+12°",
  },
  {
    date: "September 19",
    day: "Friday",
    condition: "Небольшой ливневый дождь",
    code: 1000,
    isDay: true,
    tempMax: "+18°",
    tempMin: "+12°",
  },
  {
    date: "September 20",
    day: "Saturday",
    condition: "Clear",
    code: 1000,
    isDay: false,
    tempMax: "+18°",
    tempMin: "+12°",
  },
  {
    date: "September 21",
    day: "Sunday",
    condition: "Partly Cloudy",
    code: 1000,
    isDay: true,
    tempMax: "+18°",
    tempMin: "+12°",
  },
];
